/**
 * Partner seed — 3-4 partners per category per chapter area
 * Covers all 9 arcs across 7 provinces.
 * Run: bun run src/db/seed-partners.ts
 */

import { db } from './index'
import { partners, chapterFeaturedPartners } from './schema'
import { createId } from '@paralleldrive/cuid2'

// ─── Partner definitions ──────────────────────────────────────────────────────

const PARTNERS = [

  // ══════════════════════════════════════════════════════════════════════════
  // WESTERN PROVINCE — Colombo Street Food Circuit
  // Chapters: Hoppers at Dawn (6.9271, 79.8612) | Kottu (6.9175, 79.8584) | Tea (6.9344, 79.8428)
  // ══════════════════════════════════════════════════════════════════════════

  // FOOD
  {
    id: 'p_upalis',
    name: "Upali's by Nawaloka",
    category: 'FOOD',
    tagline: 'The definitive Sinhala rice & curry in Colombo',
    description: 'A Colombo institution since 1974. The rice and curry lunch — twelve dishes, served on a banana leaf — is the benchmark by which all others are judged. Locals queue for it.',
    lat: 6.9245, lng: 79.8527,
    address: '65 D.R. Wijewardena Mawatha, Colombo 10',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 695 939', whatsapp: '+94771234567',
    tier: 'partner',
    photos: [], priceMin: 5, priceMax: 12,
    tags: ['rice-and-curry', 'local-institution', 'lunch-only', 'vegetarian-friendly'],
    openingHours: { mon: '6am–10pm', tue: '6am–10pm', wed: '6am–10pm', thu: '6am–10pm', fri: '6am–10pm', sat: '6am–10pm', sun: '6am–10pm' },
    isApproved: true,
  },
  {
    id: 'p_crab_market',
    name: 'Ministry of Crab',
    category: 'FOOD',
    tagline: 'Sri Lanka\'s most famous restaurant — lagoon crab, done perfectly',
    description: 'Set in the Dutch Hospital, an 18th-century colonial building in Colombo Fort. The Sri Lankan lagoon crabs are sourced fresh daily. Book ahead — always full.',
    lat: 6.9366, lng: 79.8432,
    address: 'Old Dutch Hospital, Hospital Street, Colombo 01',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 342 722', whatsapp: null,
    website: 'https://ministryofcrab.com',
    tier: 'premium',
    photos: [], priceMin: 25, priceMax: 70,
    tags: ['seafood', 'crab', 'fine-dining', 'colonial-building'],
    openingHours: { mon: '12pm–10pm', tue: '12pm–10pm', wed: '12pm–10pm', thu: '12pm–10pm', fri: '12pm–11pm', sat: '12pm–11pm', sun: '12pm–10pm' },
    isApproved: true,
  },
  {
    id: 'p_dinemore',
    name: 'Dinemore Kottu House',
    category: 'FOOD',
    tagline: 'The best late-night kottu in Pettah — open until 2am',
    description: 'The iron blades here have been going since 1989. Chicken kottu, cheese kottu, and the secret "special" that regulars order by name. Cash only. Expect a queue after 10pm.',
    lat: 6.9175, lng: 79.8584,
    address: 'Manning Place, Pettah, Colombo 11',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 77 345 6789', whatsapp: '+94773456789',
    tier: 'partner',
    photos: [], priceMin: 3, priceMax: 8,
    tags: ['kottu', 'street-food', 'late-night', 'cash-only'],
    openingHours: { mon: '8am–2am', tue: '8am–2am', wed: '8am–2am', thu: '8am–2am', fri: '8am–2am', sat: '8am–2am', sun: '8am–2am' },
    isApproved: true,
  },
  {
    id: 'p_pagoda_tea',
    name: 'Pagoda Tea Room',
    category: 'FOOD',
    tagline: 'Colonial-era tea room — single-estate Ceylon teas and proper egg hoppers',
    description: 'One of Colombo\'s oldest tea rooms, in a faded colonial shophouse near Viharamahadevi Park. They serve ten single-estate teas, hoppers all day, and a watalappan that takes 24 hours to set.',
    lat: 6.9344, lng: 79.8428,
    address: '17 Ananda Coomaraswamy Mawatha, Colombo 03',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 573 843', whatsapp: '+94712345678',
    tier: 'partner',
    photos: [], priceMin: 2, priceMax: 8,
    tags: ['tea', 'hoppers', 'colonial', 'vegetarian-friendly'],
    openingHours: { mon: '7am–9pm', tue: '7am–9pm', wed: '7am–9pm', thu: '7am–9pm', fri: '7am–9pm', sat: '8am–8pm', sun: '8am–6pm' },
    isApproved: true,
  },

  // STAY
  {
    id: 'p_cinnamon_grand',
    name: 'Cinnamon Grand Colombo',
    category: 'STAY',
    tagline: 'Colombo\'s landmark hotel — central, reliable, seventeen restaurants',
    description: 'The most recognisable hotel in Colombo. Five minutes from Galle Face, walking distance from the Fort. The pool is one of the city\'s best-kept secrets.',
    lat: 6.9126, lng: 79.8502,
    address: '77 Galle Rd, Colombo 03',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 437 437', whatsapp: null,
    website: 'https://cinnamonhotels.com',
    tier: 'premium',
    photos: [], priceMin: 120, priceMax: 280,
    tags: ['luxury', 'pool', 'central-location', 'multiple-restaurants'],
    openingHours: { note: 'Check-in from 2pm, check-out 12pm' },
    isApproved: true,
  },
  {
    id: 'p_colombo_court',
    name: 'Colombo Court Hotel',
    category: 'STAY',
    tagline: 'Boutique hotel in the Fort — within walking distance of everything',
    description: 'A restored 19th-century building in Colombo Fort. Sixteen rooms, a rooftop bar, and a staff who actually know the city. The breakfast includes string hoppers made fresh each morning.',
    lat: 6.9366, lng: 79.8432,
    address: '30 Alfred House Avenue, Colombo 03',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 554 497', whatsapp: '+94711234567',
    tier: 'partner',
    photos: [], priceMin: 55, priceMax: 110,
    tags: ['boutique', 'colonial', 'rooftop-bar', 'fort-location'],
    openingHours: { note: 'Check-in from 2pm, check-out 11am' },
    isApproved: true,
  },
  {
    id: 'p_nomads_colombo',
    name: 'Nomads Hostel Colombo',
    category: 'STAY',
    tagline: 'Best hostel in the city — social, clean, good breakfast',
    description: 'Colombo\'s top-rated hostel for solo travellers and backpackers. Mixed and female-only dorms, a rooftop hangout, and a weekly communal dinner. The staff book tours and know the street food scene.',
    lat: 6.9200, lng: 79.8540,
    address: '4 Guildford Crescent, Colombo 07',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 77 987 6543', whatsapp: '+94779876543',
    tier: 'listed',
    photos: [], priceMin: 12, priceMax: 35,
    tags: ['hostel', 'backpacker', 'social', 'rooftop'],
    openingHours: { note: 'Open 24 hours' },
    isApproved: true,
  },

  // EXPERIENCE
  {
    id: 'p_colombo_food_tour',
    name: 'Colombo Street Food Tours',
    category: 'EXPERIENCE',
    tagline: 'Two-hour evening walk through Pettah market and the street food strip',
    description: 'Small groups, maximum 8. You eat kottu, hoppers, isso vadai, watalappan, and king coconut at five stops. The guide grew up in Pettah and knows every cart owner personally.',
    lat: 6.9271, lng: 79.8612,
    address: 'Meet at Pettah Clock Tower, Colombo 11',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 77 456 7890', whatsapp: '+94774567890',
    tier: 'partner',
    photos: [], priceMin: 18, priceMax: 25,
    tags: ['food-tour', 'walking', 'small-group', 'evening'],
    openingHours: { note: 'Tours at 4:30pm and 7pm daily. Book 24 hours ahead.' },
    isApproved: true,
  },
  {
    id: 'p_colombo_cycling',
    name: 'Veloheads Cycling Colombo',
    category: 'EXPERIENCE',
    tagline: 'Early morning cycling tour of Colombo before the traffic wakes up',
    description: 'The only way to see Colombo without traffic is at 5:30am. This 3-hour cycling tour goes through the Fort, Pettah, the canal network, and the fish market. Bikes and helmets provided.',
    lat: 6.9340, lng: 79.8420,
    address: 'Starts at Galle Face Hotel forecourt',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 77 234 5678', whatsapp: '+94772345678',
    tier: 'partner',
    photos: [], priceMin: 22, priceMax: 30,
    tags: ['cycling', 'early-morning', 'small-group', 'includes-breakfast'],
    openingHours: { note: 'Tours at 5:30am daily. Book 48 hours ahead.' },
    isApproved: true,
  },

  // TRANSPORT
  {
    id: 'p_fort_tuktuk',
    name: 'Colombo Fort Tuk-Tuks',
    category: 'TRANSPORT',
    tagline: 'Metered tuk-tuks from the Fort — fair price, no negotiation needed',
    description: 'A co-operative of 22 tuk-tuk drivers operating from Colombo Fort. All vehicles have meters. English-speaking. WhatsApp to book a pickup anywhere in Colombo 1–7.',
    lat: 6.9340, lng: 79.8420,
    address: 'Colombo Fort Railway Station rank',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 77 111 2222', whatsapp: '+94771112222',
    tier: 'listed',
    photos: [], priceMin: 2, priceMax: 10,
    tags: ['tuk-tuk', 'metered', 'english-speaking', 'reliable'],
    openingHours: { note: 'Available 5am–midnight daily' },
    isApproved: true,
  },

  // SHOP
  {
    id: 'p_laksala_colombo',
    name: 'Laksala Government Crafts',
    category: 'SHOP',
    tagline: 'Government-run craft shop — fixed prices, authentic souvenirs',
    description: 'Laksala is the Sri Lanka state crafts chain. Fixed prices mean no haggling, and authenticity is guaranteed. Good for: batik, brasswork, lacquerware, wooden masks, and handloom textiles.',
    lat: 6.9200, lng: 79.8500,
    address: '26 Svarna Mahal, Sir Baron Jayatilaka Mawatha, Colombo 01',
    district: 'Colombo', province: 'WESTERN',
    phone: '+94 11 2 329 817', whatsapp: null,
    tier: 'listed',
    photos: [], priceMin: 5, priceMax: 150,
    tags: ['crafts', 'fixed-price', 'government', 'authentic'],
    openingHours: { mon: '9am–6pm', tue: '9am–6pm', wed: '9am–6pm', thu: '9am–6pm', fri: '9am–6pm', sat: '9am–5pm', sun: 'closed' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHERN PROVINCE — Yala Leopard + Surf South Coast + Galle Fort
  // ══════════════════════════════════════════════════════════════════════════

  // YALA AREA (6.41, 81.51)
  {
    id: 'p_yala_wild_camp',
    name: 'Yala Wild Camp',
    category: 'STAY',
    tagline: 'Canvas tents at the Yala buffer zone — fall asleep to jackals',
    description: 'Twelve tented chalets inside the Yala buffer zone. You can hear the peacocks from your bed. The camp arranges private dawn safaris that enter before the main gates open to day visitors.',
    lat: 6.4200, lng: 81.4800,
    address: 'Palatupana, Yala',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 77 888 9900', whatsapp: '+94778889900',
    tier: 'premium',
    photos: [], priceMin: 180, priceMax: 380,
    tags: ['tented-camp', 'safari', 'wildlife', 'all-inclusive'],
    openingHours: { note: 'Check-in 2pm, check-out 11am. Min 2 nights.' },
    isApproved: true,
  },
  {
    id: 'p_chena_huts',
    name: 'Chena Huts by Uga Escapes',
    category: 'STAY',
    tagline: 'The most beautiful eco-lodge at Yala — private plunge pools and sunset elephants',
    description: 'Thirty chalets on stilts looking into the park. The infinity pool lines up with the tree line where elephants appear every evening. The food is exceptional — Sri Lankan tasting menus using local produce.',
    lat: 6.4000, lng: 81.5100,
    address: 'Yala National Park Buffer Zone, Kirinda',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 11 2 302 500', whatsapp: null,
    website: 'https://ugaescapes.com',
    tier: 'premium',
    photos: [], priceMin: 350, priceMax: 650,
    tags: ['luxury', 'eco-lodge', 'plunge-pool', 'wildlife-views'],
    openingHours: { note: 'Open year round. Book minimum 2 nights.' },
    isApproved: true,
  },
  {
    id: 'p_yala_jeep_safari',
    name: 'Ranga Yala Safari',
    category: 'EXPERIENCE',
    tagline: 'Fifteen years tracking Yala\'s leopards — the guide who finds them',
    description: 'Ranga has been leading safaris in Yala since 2009. He tracks individual leopards by markings and knows their territories. Half-day and full-day private and shared jeep safaris. Pick-up from Tissamaharama.',
    lat: 6.4167, lng: 81.5139,
    address: 'Palatupana Gate, Yala National Park',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 77 321 4567', whatsapp: '+94773214567',
    tier: 'partner',
    photos: [], priceMin: 45, priceMax: 120,
    tags: ['safari', 'leopard', 'private-guide', 'half-day'],
    openingHours: { note: 'Safaris at 6am and 3pm daily. Book 2 days ahead.' },
    isApproved: true,
  },
  {
    id: 'p_yala_camp_kitchen',
    name: 'Lunuganga Rest & Kitchen',
    category: 'FOOD',
    tagline: 'The only proper meal between Tissamaharama and the park gate',
    description: 'A family-run kitchen serving hearty rice and curry, devilled prawns, and coconut sambol from a shaded garden. Run by a former park guide\'s family. Everything is cooked fresh — expect to wait 20 minutes and not regret it.',
    lat: 6.4500, lng: 81.5000,
    address: 'Kirinda Road, Palatupana',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 77 654 3210', whatsapp: '+94776543210',
    tier: 'listed',
    photos: [], priceMin: 4, priceMax: 10,
    tags: ['rice-and-curry', 'family-run', 'fresh-seafood', 'garden'],
    openingHours: { mon: '7am–9pm', tue: '7am–9pm', wed: '7am–9pm', thu: '7am–9pm', fri: '7am–9pm', sat: '7am–9pm', sun: '7am–9pm' },
    isApproved: true,
  },
  {
    id: 'p_yala_transport',
    name: 'Tissa Jeep Hire',
    category: 'TRANSPORT',
    tagline: 'Jeeps and drivers from Tissamaharama — reliable, fair-priced',
    description: 'A fleet of twenty 4WD jeeps operating from Tissamaharama town. Full-day hire includes driver. Good for Yala, Udawalawe, and Bundala. WhatsApp for same-day availability.',
    lat: 6.2830, lng: 81.2870,
    address: 'Main Street, Tissamaharama',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 77 777 6655', whatsapp: '+94777776655',
    tier: 'listed',
    photos: [], priceMin: 50, priceMax: 100,
    tags: ['4wd', 'jeep', 'driver-included', 'day-hire'],
    openingHours: { note: 'Available 24 hours. WhatsApp for bookings.' },
    isApproved: true,
  },

  // WELIGAMA / SURF AREA (5.97, 80.43)
  {
    id: 'p_weligama_surf_school',
    name: 'Weligama Surf School',
    category: 'EXPERIENCE',
    tagline: 'Learn to surf in one lesson — small groups, patient instructors',
    description: 'The original surf school in Weligama, running since 2006. Maximum 4 students per instructor. Two-hour lessons include board, rashguard, and a post-session coconut. Guaranteed to stand up or your next lesson is free.',
    lat: 5.9738, lng: 80.4290,
    address: 'Weligama Bay Beach, Main Road, Weligama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 444 5566', whatsapp: '+94774445566',
    tier: 'premium',
    photos: [], priceMin: 18, priceMax: 25,
    tags: ['surf-lessons', 'beginner-friendly', 'board-hire', 'small-group'],
    openingHours: { note: 'Lessons at 7am, 9am, 2pm, 4pm. Walk-ins welcome.' },
    isApproved: true,
  },
  {
    id: 'p_madiha_surf',
    name: 'Madiha Point Surf Academy',
    category: 'EXPERIENCE',
    tagline: 'Intermediate and advanced surf coaching at Midigama reef',
    description: 'The go-to school for surfers who already know the basics. Video analysis, reef reading clinics, and custom coaching sessions. Board hire available. The instructors surf Midigama every day and know the break intimately.',
    lat: 5.9697, lng: 80.3742,
    address: 'Midigama Village, Midigama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 567 8901', whatsapp: '+94775678901',
    tier: 'partner',
    photos: [], priceMin: 20, priceMax: 40,
    tags: ['intermediate', 'reef-break', 'video-analysis', 'board-hire'],
    openingHours: { note: 'Daily 6am–5pm. Book coaching 24h ahead.' },
    isApproved: true,
  },
  {
    id: 'p_taprobana',
    name: 'Taprobana Island Hotel',
    category: 'STAY',
    tagline: 'A private island hotel in Weligama Bay — 22 rooms, zero cars',
    description: 'Accessible only by boat. Twenty-two ocean-facing rooms, a sea-view pool, and the most extraordinary location in southern Sri Lanka. The restaurant serves the catch of the day, brought in by the stilt fishermen you can see from your terrace.',
    lat: 5.9750, lng: 80.4310,
    address: 'Taprobana Island, Weligama Bay',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 41 2 209 100', whatsapp: null,
    website: 'https://taprobana.com',
    tier: 'premium',
    photos: [], priceMin: 220, priceMax: 480,
    tags: ['island-hotel', 'private', 'no-cars', 'sea-view'],
    openingHours: { note: 'Check-in 2pm. Boat transfers from Weligama beach.' },
    isApproved: true,
  },
  {
    id: 'p_dream_surf_hostel',
    name: 'Dream Surf Hostel',
    category: 'STAY',
    tagline: 'Right on Weligama Bay — wake up, walk 20m, surf',
    description: 'The best-located budget accommodation in Weligama. The beach is twenty steps from the front door. Board storage, rinse area, and a breezy common room where you can watch the waves while eating breakfast.',
    lat: 5.9730, lng: 80.4280,
    address: 'Bay Road, Weligama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 234 5670', whatsapp: '+94772345670',
    tier: 'listed',
    photos: [], priceMin: 12, priceMax: 45,
    tags: ['hostel', 'beachfront', 'board-storage', 'surf-crowd'],
    openingHours: { note: 'Open 24 hours. Check-in from 1pm.' },
    isApproved: true,
  },
  {
    id: 'p_wijaya_kitchen',
    name: 'Wijaya Beach Kitchen',
    category: 'FOOD',
    tagline: 'Grilled tuna and coconut curries on the Weligama waterfront',
    description: 'A beach shack that has been upgraded over twenty years into a proper restaurant without losing any of its soul. The tuna is caught daily from the bay. The coconut curry is made from scratch every morning. Tables on the sand.',
    lat: 5.9738, lng: 80.4300,
    address: 'Beach Road, Weligama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 888 1234', whatsapp: '+94778881234',
    tier: 'partner',
    photos: [], priceMin: 6, priceMax: 18,
    tags: ['seafood', 'beach-dining', 'fresh-tuna', 'coconut-curry'],
    openingHours: { mon: '7am–10pm', tue: '7am–10pm', wed: '7am–10pm', thu: '7am–10pm', fri: '7am–11pm', sat: '7am–11pm', sun: '7am–10pm' },
    isApproved: true,
  },
  {
    id: 'p_mango_cafe',
    name: 'Mango Garden Cafe',
    category: 'FOOD',
    tagline: 'Smoothie bowls, sourdough toast, and very good iced coffee at Midigama',
    description: 'Run by a family who returned from Australia. The menu bridges Sri Lankan and Western — acai bowls sit next to pol roti, and the cold brew is the best on the south coast. The garden fills up fast after morning surf.',
    lat: 5.9697, lng: 80.3740,
    address: 'Midigama Main Road, Midigama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 345 6780', whatsapp: '+94773456780',
    tier: 'partner',
    photos: [], priceMin: 4, priceMax: 12,
    tags: ['cafe', 'smoothie-bowls', 'post-surf', 'cold-brew'],
    openingHours: { mon: '7am–4pm', tue: '7am–4pm', wed: 'closed', thu: '7am–4pm', fri: '7am–5pm', sat: '7am–5pm', sun: '7am–3pm' },
    isApproved: true,
  },
  {
    id: 'p_hiriketiya_bowls',
    name: 'Hiriketiya Kitchen',
    category: 'FOOD',
    tagline: 'The smoothie bowls that made Hiriketiya famous — worth the hype',
    description: 'The open-air kitchen that started the Hiriketiya cafe scene. Dragon fruit bowls, fresh papaya, Sri Lankan-spiced granola, and a coconut shakshuka that people specifically drive from Galle for. Gets busy from 8am.',
    lat: 5.9441, lng: 80.4453,
    address: 'Hiriketiya Beach Road, Hiriketiya',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 456 7891', whatsapp: '+94774567891',
    tier: 'partner',
    photos: [], priceMin: 5, priceMax: 14,
    tags: ['smoothie-bowls', 'breakfast', 'organic', 'beach-cove'],
    openingHours: { mon: '7am–3pm', tue: '7am–3pm', wed: 'closed', thu: '7am–3pm', fri: '7am–4pm', sat: '7am–4pm', sun: '7am–3pm' },
    isApproved: true,
  },
  {
    id: 'p_anantara_hiriketiya',
    name: 'Anantara Peace Haven Tangalle',
    category: 'STAY',
    tagline: 'Clifftop resort above Hiriketiya — infinity pool, spa, world-class service',
    description: 'The finest resort on the south coast. Built into a headland above the sea. The ayurveda spa, the infinity pool, and the reef snorkelling are all exceptional. The beach below the resort is one of the quietest on the coast.',
    lat: 5.9440, lng: 80.4450,
    address: 'Goyambokka Estate, Tangalle',
    district: 'Hambantota', province: 'SOUTHERN',
    phone: '+94 47 4 889 100', whatsapp: null,
    website: 'https://anantara.com',
    tier: 'premium',
    photos: [], priceMin: 280, priceMax: 600,
    tags: ['luxury', 'infinity-pool', 'spa', 'clifftop'],
    openingHours: { note: 'Check-in 3pm. Guests also welcome from Hiriketiya Beach.' },
    isApproved: true,
  },
  {
    id: 'p_south_transport',
    name: 'South Coast Driver Co.',
    category: 'TRANSPORT',
    tagline: 'Private drivers and transfers — Galle to Mirissa, Matara, Tangalle',
    description: 'A co-operative of twelve experienced drivers covering the south coast from Galle to Tangalle. A/C vehicles, clean, punctual. Airport pickups, day tours, and intercity transfers. All drivers speak English.',
    lat: 5.9700, lng: 80.4200,
    address: 'Weligama Bus Stand, Weligama',
    district: 'Matara', province: 'SOUTHERN',
    phone: '+94 77 999 1234', whatsapp: '+94779991234',
    tier: 'listed',
    photos: [], priceMin: 15, priceMax: 80,
    tags: ['private-driver', 'a/c', 'airport-transfers', 'english-speaking'],
    openingHours: { note: 'Available 5am–11pm. Book via WhatsApp.' },
    isApproved: true,
  },

  // GALLE FORT AREA (6.027, 80.217)
  {
    id: 'p_fortaleza',
    name: 'Fortaleza Restaurant',
    category: 'FOOD',
    tagline: 'Sri Lankan cuisine reimagined — inside a 17th-century Dutch building',
    description: 'Named after the Portuguese word for fort. The kitchen uses traditional Sri Lankan recipes and local produce, plated with precision. The lamprais — rice, curry, cutlet, wrapped in banana leaf and baked — takes 48 hours to prepare.',
    lat: 6.0270, lng: 80.2160,
    address: '39 Leyn Baan Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 91 2 234 567', whatsapp: '+94912234567',
    tier: 'partner',
    photos: [], priceMin: 12, priceMax: 30,
    tags: ['sri-lankan', 'fine-dining', 'lamprais', 'colonial-setting'],
    openingHours: { mon: '12pm–10pm', tue: '12pm–10pm', wed: '12pm–10pm', thu: '12pm–10pm', fri: '12pm–11pm', sat: '12pm–11pm', sun: '12pm–10pm' },
    isApproved: true,
  },
  {
    id: 'p_fort_printers',
    name: 'Fort Printers Restaurant',
    category: 'FOOD',
    tagline: 'The old print works is now Galle Fort\'s most atmospheric restaurant',
    description: 'An 18th-century Dutch printing house converted into a twelve-table restaurant. The menu changes daily and leans heavily on the morning\'s catch and the garden. Reservations essential — it fills two weeks in advance.',
    lat: 6.0280, lng: 80.2170,
    address: '39 Pedlar Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 91 2 247 977', whatsapp: null,
    tier: 'premium',
    photos: [], priceMin: 18, priceMax: 45,
    tags: ['tasting-menu', 'reservations-required', 'colonial', 'farm-to-table'],
    openingHours: { tue: '7pm–10pm', wed: '7pm–10pm', thu: '7pm–10pm', fri: '7pm–10pm', sat: '12pm–3pm', sun: '12pm–3pm', note: 'Closed Monday' },
    isApproved: true,
  },
  {
    id: 'p_dutch_market_cafe',
    name: 'Old Dutch Market Cafe',
    category: 'FOOD',
    tagline: 'Morning coffee and egg hoppers inside the ramparts — the best breakfast in Galle',
    description: 'A small, low-key cafe inside the fort walls serving Sri Lankan breakfast from 7am. The egg hopper with sambol and coconut milk is the standard order. Tables spill out onto a courtyard. Cash only.',
    lat: 6.0265, lng: 80.2155,
    address: '4 Church Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 77 234 5690', whatsapp: '+94772345690',
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 9,
    tags: ['breakfast', 'hoppers', 'cash-only', 'courtyard'],
    openingHours: { mon: '7am–1pm', tue: '7am–1pm', wed: '7am–1pm', thu: '7am–1pm', fri: '7am–1pm', sat: '7am–2pm', sun: '8am–12pm' },
    isApproved: true,
  },
  {
    id: 'p_amangalla',
    name: 'Amangalla',
    category: 'STAY',
    tagline: 'The most historically significant hotel in Sri Lanka — inside the fort since 1684',
    description: 'This building has been a place of accommodation since the Dutch East India Company built it as the New Oriental Hotel in 1684. Today it is an Aman property: thirty suites, a colonial plunge pool, and an afternoon tea that takes two hours. It is less a hotel than a time machine.',
    lat: 6.0271, lng: 80.2165,
    address: '10 Church Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 91 2 233 388', whatsapp: null,
    website: 'https://aman.com/hotels/amangalla',
    tier: 'premium',
    photos: [], priceMin: 550, priceMax: 1200,
    tags: ['aman', 'historic', 'luxury', 'within-fort-walls'],
    openingHours: { note: 'Open year-round. Check-in 3pm.' },
    isApproved: true,
  },
  {
    id: 'p_galle_fort_hotel',
    name: 'Galle Fort Hotel',
    category: 'STAY',
    tagline: 'Boutique hotel in a 17th-century merchant\'s house — 14 rooms, rooftop pool',
    description: 'Converted from a Dutch merchant\'s residence. Fourteen rooms each individually designed using antique furniture and Sri Lankan textiles. The rooftop pool looks over the fort walls and the sea. The breakfast is served in the colonial courtyard.',
    lat: 6.0275, lng: 80.2170,
    address: '28 Church Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 91 2 232 870', whatsapp: '+94912232870',
    website: 'https://galleforthotel.com',
    tier: 'premium',
    photos: [], priceMin: 180, priceMax: 350,
    tags: ['boutique', 'rooftop-pool', 'colonial', 'within-fort-walls'],
    openingHours: { note: 'Check-in 2pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_fort_walking_tour',
    name: 'Chaminda\'s Fort Walks',
    category: 'EXPERIENCE',
    tagline: 'The fort with a local guide who was born here — not the tourist version',
    description: 'Chaminda\'s family has lived inside the fort for four generations. His 90-minute walking tour covers the buildings tourists miss: the Dutch warehouses, the private family temples, the cisterns under the streets. Maximum 6 guests. Available in English and basic French.',
    lat: 6.0276, lng: 80.2165,
    address: 'Meets at the Fort Gate',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 77 654 3211', whatsapp: '+94776543211',
    tier: 'partner',
    photos: [], priceMin: 15, priceMax: 20,
    tags: ['walking-tour', 'local-guide', 'small-group', 'history'],
    openingHours: { note: 'Tours at 8:30am and 4pm daily. Book by 8pm the night before.' },
    isApproved: true,
  },
  {
    id: 'p_barefoot_galle',
    name: 'Barefoot Galle',
    category: 'SHOP',
    tagline: 'Handwoven textiles, batik, and ceramics — the best craft shop on the south coast',
    description: 'The Galle outpost of the famous Colombo design brand. Handwoven cotton and linen in Sri Lankan patterns, handmade ceramics, illustrated maps, and small accessories. Everything is made in Sri Lanka.',
    lat: 6.0272, lng: 80.2162,
    address: '41 Pedlar Street, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 91 2 245 641', whatsapp: null,
    tier: 'partner',
    photos: [], priceMin: 8, priceMax: 120,
    tags: ['handwoven', 'batik', 'ceramics', 'made-in-sri-lanka'],
    openingHours: { mon: '9am–6pm', tue: '9am–6pm', wed: '9am–6pm', thu: '9am–6pm', fri: '9am–6pm', sat: '9am–6pm', sun: '10am–4pm' },
    isApproved: true,
  },
  {
    id: 'p_galle_cycling',
    name: 'Galle Cycle Tours',
    category: 'EXPERIENCE',
    tagline: 'Cycle inside the fort and out to the lagoon fishing villages',
    description: 'Three-hour morning ride: the fort, the Dutch canal, Unawatuna lagoon, and a fishing village breakfast. Hybrid bikes, helmets, and a local guide included. Suitable for all fitness levels. Book by 7pm the night before.',
    lat: 6.0265, lng: 80.2160,
    address: 'Meets at the Flag Rock, Galle Fort',
    district: 'Galle', province: 'SOUTHERN',
    phone: '+94 77 567 8902', whatsapp: '+94775678902',
    tier: 'listed',
    photos: [], priceMin: 20, priceMax: 28,
    tags: ['cycling', 'fishing-village', 'morning-tour', 'lagoon'],
    openingHours: { note: 'Daily 7am departure. Book by 7pm the night before.' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SABARAGAMUWA PROVINCE — Udawalawe
  // Chapters: Reservoir (6.4833, 80.9000) | Elephant Transit (6.4711, 80.9167)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'p_centauria_wild',
    name: 'Centauria Wild Hotel',
    category: 'STAY',
    tagline: 'The closest lodge to the park gates — elephants on the lawn at dusk',
    description: 'Forty eco-friendly rooms bordering Udawalawe park. The resident herd comes to the water tank behind the property every evening. The camp arranges private safaris with the park\'s best trackers.',
    lat: 6.4800, lng: 80.9100,
    address: 'Udawalawe, Embilipitiya Road',
    district: 'Ratnapura', province: 'SABARAGAMUWA',
    phone: '+94 47 3 560 225', whatsapp: '+94473560225',
    tier: 'partner',
    photos: [], priceMin: 85, priceMax: 180,
    tags: ['eco-lodge', 'wildlife-views', 'safari', 'elephants'],
    openingHours: { note: 'Check-in 2pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_kalus_hideaway',
    name: "Kalu's Hideaway",
    category: 'STAY',
    tagline: 'Small family guesthouse — homemade curry, cold beer, local knowledge',
    description: "Kalu and his wife Nanda have been hosting travellers for fifteen years. Eight rooms, a garden, and the kind of Sri Lankan home cooking you can't find in restaurants. Kalu drives his own jeep and leads safaris himself.",
    lat: 6.5000, lng: 80.9000,
    address: 'Udawalawe Town, off the main road',
    district: 'Ratnapura', province: 'SABARAGAMUWA',
    phone: '+94 77 432 1098', whatsapp: '+94774321098',
    tier: 'listed',
    photos: [], priceMin: 25, priceMax: 60,
    tags: ['guesthouse', 'home-cooking', 'family-run', 'local-guide'],
    openingHours: { note: 'Open year-round. Book in advance.' },
    isApproved: true,
  },
  {
    id: 'p_udawalawe_safari',
    name: 'Udawalawe Tracker Safaris',
    category: 'EXPERIENCE',
    tagline: 'Certified guides who know every watering hole — 700 elephants, guaranteed',
    description: 'The best-reviewed safari operator at Udawalawe. Private and shared jeeps, half-day and full-day. The guides can identify individual elephants by ear shape and are expert at finding the resident leopard in the northern section.',
    lat: 6.4833, lng: 80.9000,
    address: 'Udawalawe National Park Main Gate',
    district: 'Ratnapura', province: 'SABARAGAMUWA',
    phone: '+94 77 123 4560', whatsapp: '+94771234560',
    tier: 'partner',
    photos: [], priceMin: 35, priceMax: 90,
    tags: ['safari', 'elephants', 'private-guide', 'half-day'],
    openingHours: { note: 'Gate opens 6am and 3pm. Book 24h ahead.' },
    isApproved: true,
  },
  {
    id: 'p_udawalawe_food',
    name: 'Elephant View Resto',
    category: 'FOOD',
    tagline: 'Simple Sri Lankan food opposite the park entrance — best pol sambol on the road',
    description: 'A no-frills restaurant facing the park boundary. The rice and curry lunch is cooked fresh each morning. The owner has lived here for forty years and can tell you about the park like no brochure ever could.',
    lat: 6.4850, lng: 80.8990,
    address: 'Udawalawe Main Road, near Park Gate',
    district: 'Ratnapura', province: 'SABARAGAMUWA',
    phone: '+94 77 654 3219', whatsapp: '+94776543219',
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 8,
    tags: ['rice-and-curry', 'local', 'budget', 'post-safari'],
    openingHours: { mon: '6am–9pm', tue: '6am–9pm', wed: '6am–9pm', thu: '6am–9pm', fri: '6am–9pm', sat: '6am–9pm', sun: '6am–9pm' },
    isApproved: true,
  },
  {
    id: 'p_elephant_watch',
    name: 'Elephant Watch Experience',
    category: 'EXPERIENCE',
    tagline: 'Guided observation at the Transit Home feeding sessions',
    description: 'A naturalist-led experience at the Elephant Transit Home feeding times. Understand elephant behaviour, rehabilitation ethics, and what happens after the orphans are released. Small groups, insightful commentary.',
    lat: 6.4711, lng: 80.9167,
    address: 'Elephant Transit Home, Udawalawe',
    district: 'Ratnapura', province: 'SABARAGAMUWA',
    phone: '+94 77 234 5688', whatsapp: '+94772345688',
    tier: 'listed',
    photos: [], priceMin: 10, priceMax: 15,
    tags: ['elephant-conservation', 'guided', 'educational', 'family-friendly'],
    openingHours: { note: 'Feeding times: 9am, 12pm, 3pm, 6pm. Arrive 20 min early.' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // UVA PROVINCE — Ella Trails
  // Chapters: Nine Arches (6.8750, 81.0590) | Ella Rock (6.8600, 81.0460)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'p_98_acres',
    name: '98 Acres Resort & Spa',
    category: 'STAY',
    tagline: 'Tea estate resort with the most spectacular view of the Ella Gap',
    description: 'Set on a working tea estate above Ella village. The infinity pool appears to float above the valley. The spa uses locally grown herbs for its treatments. The estate walk at dawn, through the tea bushes in the mist, is included for all guests.',
    lat: 6.8760, lng: 81.0510,
    address: '98 Acres Estate, Ella',
    district: 'Badulla', province: 'UVA',
    phone: '+94 57 2 228 888', whatsapp: null,
    website: 'https://98acres.com',
    tier: 'premium',
    photos: [], priceMin: 150, priceMax: 350,
    tags: ['tea-estate', 'infinity-pool', 'spa', 'ella-gap-views'],
    openingHours: { note: 'Check-in 2pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_ella_flower_garden',
    name: 'Ella Flower Garden Resort',
    category: 'STAY',
    tagline: 'Family-run hillside resort with valley views and excellent home cooking',
    description: 'A forty-room resort built into the hillside above Ella junction, with direct views of Ella Rock. The restaurant serves traditional Sri Lankan food made by the owner\'s mother. A reliable, honest option at a fair price.',
    lat: 6.8740, lng: 81.0585,
    address: 'Main Street, Ella',
    district: 'Badulla', province: 'UVA',
    phone: '+94 57 2 228 541', whatsapp: '+94572228541',
    tier: 'partner',
    photos: [], priceMin: 40, priceMax: 85,
    tags: ['family-run', 'valley-views', 'home-cooking', 'ella-rock'],
    openingHours: { note: 'Check-in 12pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_ella_adventure',
    name: 'Ella Adventure Guides',
    category: 'EXPERIENCE',
    tagline: 'Local guides for Ella Rock, Little Adam\'s Peak, and Ravana Falls',
    description: 'A team of six local guides who know every unmarked trail around Ella. The Ella Rock route changes by season — they know which path avoids the leeches and which shortcut saves 40 minutes. Guides speak English and carry first aid.',
    lat: 6.8750, lng: 81.0590,
    address: 'Ella Junction, Ella Main Street',
    district: 'Badulla', province: 'UVA',
    phone: '+94 77 876 5432', whatsapp: '+94778765432',
    tier: 'partner',
    photos: [], priceMin: 12, priceMax: 20,
    tags: ['hiking-guide', 'ella-rock', 'little-adams-peak', 'local'],
    openingHours: { note: 'Meet at 6am for Ella Rock. Book the night before.' },
    isApproved: true,
  },
  {
    id: 'p_cafe_chill_ella',
    name: 'Cafe Chill Ella',
    category: 'FOOD',
    tagline: 'Rooftop cafe above Ella station — the best view for the 8:47am train',
    description: 'A three-storey cafe with a roof terrace that has a direct view of the Nine Arches Bridge. The timing is everything here: order a banana pancake, find a spot on the roof, and watch the blue train pass through. Sri Lankan and Western breakfast served all day.',
    lat: 6.8745, lng: 81.0590,
    address: 'Ella Station Road, Ella',
    district: 'Badulla', province: 'UVA',
    phone: '+94 77 345 6701', whatsapp: '+94773456701',
    tier: 'partner',
    photos: [], priceMin: 3, priceMax: 10,
    tags: ['rooftop', 'nine-arches-view', 'train', 'breakfast-all-day'],
    openingHours: { mon: '7am–8pm', tue: '7am–8pm', wed: '7am–8pm', thu: '7am–8pm', fri: '7am–9pm', sat: '7am–9pm', sun: '7am–8pm' },
    isApproved: true,
  },
  {
    id: 'p_ella_gap_restaurant',
    name: 'Ella Gap Tourist Rest',
    category: 'FOOD',
    tagline: 'Classic traveller stop — roti, curry, and the view of the gap',
    description: 'The oldest restaurant in Ella, on the cliff edge with the valley below. No frills, no menu changes in twenty years — just reliable Sri Lankan food at a fair price. The papaya juice is made fresh. The view is free.',
    lat: 6.8750, lng: 81.0595,
    address: 'Ella Gap Road, Ella',
    district: 'Badulla', province: 'UVA',
    phone: '+94 57 2 228 667', whatsapp: null,
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 9,
    tags: ['valley-view', 'classic', 'budget', 'local-food'],
    openingHours: { mon: '7am–9pm', tue: '7am–9pm', wed: '7am–9pm', thu: '7am–9pm', fri: '7am–9pm', sat: '7am–9pm', sun: '7am–9pm' },
    isApproved: true,
  },
  {
    id: 'p_ella_train_booking',
    name: 'Ella Express Train Booking',
    category: 'TRANSPORT',
    tagline: 'Book your Kandy-Ella or Colombo-Ella train tickets without the queue',
    description: 'The Kandy-to-Ella train is one of the most beautiful train journeys in the world. This local service agent books second and first class reserved seats on your behalf, picking up tickets from the station for a small service fee. WhatsApp the dates and they handle it.',
    lat: 6.8755, lng: 81.0598,
    address: 'Ella Railway Station, Ella',
    district: 'Badulla', province: 'UVA',
    phone: '+94 77 987 5432', whatsapp: '+94779875432',
    tier: 'listed',
    photos: [], priceMin: 2, priceMax: 5,
    tags: ['train-tickets', 'booking-agent', 'kandy-ella', 'scenic-train'],
    openingHours: { note: 'WhatsApp only. Reply within 2 hours.' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CENTRAL PROVINCE — Tea Country Reset (Nuwara Eliya)
  // Chapters: Pedro Tea Estate (6.9745, 80.7730) | Gregory Lake (6.9567, 80.7718) | Horton Plains (6.8019, 80.8046)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'p_grand_hotel_ne',
    name: 'The Grand Hotel Nuwara Eliya',
    category: 'STAY',
    tagline: 'Built in 1891 as the governor\'s summer residence — old England in the hills',
    description: 'A Victorian relic at 1,884 metres. Billiard room, wood-panelled dining room, open fireplaces, and a snooker table. The grounds are immaculate. The afternoon tea in the colonial lounge is a ritual.',
    lat: 6.9590, lng: 80.7730,
    address: 'Grand Hotel Road, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 52 2 222 881', whatsapp: null,
    website: 'https://tangerinehotels.com',
    tier: 'premium',
    photos: [], priceMin: 90, priceMax: 200,
    tags: ['colonial', 'victorian', 'fireplaces', 'afternoon-tea'],
    openingHours: { note: 'Check-in 2pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_heritance_tea',
    name: 'Heritance Tea Factory',
    category: 'STAY',
    tagline: 'A working tea factory converted into a hotel — you can smell the leaves',
    description: 'The building is a genuine 1950s tea factory. The machinery still exists — guests can watch tea being processed. The rooms use the old drying chambers and sorting rooms. At 1,800 metres, the mist in the morning is extraordinary.',
    lat: 7.0000, lng: 80.7500,
    address: 'Kandapola, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 52 2 229 600', whatsapp: null,
    website: 'https://cinnamonhotels.com',
    tier: 'premium',
    photos: [], priceMin: 160, priceMax: 320,
    tags: ['tea-factory-hotel', 'cloud-forest', 'unique-stay', 'mist'],
    openingHours: { note: 'Check-in 2pm. The tea factory operates 7am–5pm.' },
    isApproved: true,
  },
  {
    id: 'p_pedro_tours',
    name: 'Pedro Tea Estate Tours',
    category: 'EXPERIENCE',
    tagline: 'Walk the tea fields and see how orange pekoe is made from leaf to tin',
    description: 'The hour-long tour of Pedro Estate covers the picking fields, the withering troughs, the rolling machines, and the grading room. The tour guide has worked at Pedro for twenty-three years and can identify tea grades by colour and smell. Tasting included.',
    lat: 6.9745, lng: 80.7730,
    address: 'Pedro Estate, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 52 2 222 318', whatsapp: '+94522222318',
    tier: 'partner',
    photos: [], priceMin: 5, priceMax: 8,
    tags: ['tea-tour', 'factory', 'tasting', 'educational'],
    openingHours: { mon: '8am–4pm', tue: '8am–4pm', wed: '8am–4pm', thu: '8am–4pm', fri: '8am–4pm', note: 'Closed weekends' },
    isApproved: true,
  },
  {
    id: 'p_hill_club',
    name: 'The Hill Club Restaurant',
    category: 'FOOD',
    tagline: 'Colonial members\' club, now open to visitors — dinner jacket optional',
    description: 'The Hill Club was founded in 1876 for British planters. The dining room still has the original portraits. The set dinner — soup, roast, pudding — is served by waiters in white gloves. Surreal, impeccably maintained, and completely worth it.',
    lat: 6.9590, lng: 80.7725,
    address: '29 Grand Hotel Road, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 52 2 222 653', whatsapp: null,
    tier: 'premium',
    photos: [], priceMin: 20, priceMax: 45,
    tags: ['colonial', 'fine-dining', 'historic', 'set-menu'],
    openingHours: { note: 'Dinner 7pm–10pm. Reservations required. Smart casual.' },
    isApproved: true,
  },
  {
    id: 'p_lakeside_ne',
    name: 'Lakeside Restaurant',
    category: 'FOOD',
    tagline: 'Hot rice and curry on the Gregory Lake shore — warm up after the walk',
    description: 'A straightforward Sri Lankan restaurant facing Gregory Lake. The kottu is made fresh on request, the fish curry is the local specialty, and the hot ginger tea is exactly what you need at 1,800 metres. Simple and reliable.',
    lat: 6.9570, lng: 80.7720,
    address: 'Lake Road, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 52 2 223 451', whatsapp: '+94522223451',
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 8,
    tags: ['rice-and-curry', 'lakeside', 'kottu', 'budget'],
    openingHours: { mon: '7am–9pm', tue: '7am–9pm', wed: '7am–9pm', thu: '7am–9pm', fri: '7am–10pm', sat: '7am–10pm', sun: '7am–9pm' },
    isApproved: true,
  },
  {
    id: 'p_nuwara_eliya_cycling',
    name: 'Hill Country Cycling',
    category: 'EXPERIENCE',
    tagline: 'Cycle through tea estates and cloud forest at 1,800 metres',
    description: 'A three-hour morning cycling route through the Pedro tea estate, the Horton Plains buffer forest, and the Victoria Park. Hybrid bikes with quality gears for the hills. Guide included. Hot tea break at a working estate halfway through.',
    lat: 6.9570, lng: 80.7718,
    address: 'Victoria Park, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 77 876 5421', whatsapp: '+94778765421',
    tier: 'partner',
    photos: [], priceMin: 25, priceMax: 35,
    tags: ['cycling', 'tea-estate', 'cloud-forest', 'morning-tour'],
    openingHours: { note: 'Daily at 7am. Book by 9pm the night before.' },
    isApproved: true,
  },
  {
    id: 'p_ne_transport',
    name: 'Nuwara Eliya Car Hire',
    category: 'TRANSPORT',
    tagline: 'Driver-guide for Horton Plains, Adam\'s Peak, and Kandy–Ella train connections',
    description: 'Experienced drivers with 4WD vehicles for Horton Plains and the Nuwara Eliya hill country. Specialise in early morning Horton Plains departures (4am) and train-to-hotel transfers. All drivers have completed the hill country driver certification.',
    lat: 6.9580, lng: 80.7730,
    address: 'Nuwara Eliya Bus Stand, Nuwara Eliya',
    district: 'Nuwara Eliya', province: 'CENTRAL',
    phone: '+94 77 111 3333', whatsapp: '+94771113333',
    tier: 'listed',
    photos: [], priceMin: 20, priceMax: 70,
    tags: ['4wd', 'horton-plains', 'early-morning', 'train-transfers'],
    openingHours: { note: 'Available 24 hours. Book by WhatsApp.' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — Jaffna Table
  // Chapters: Jaffna Market (9.6615, 80.0088) | Crab Curry Lagoon (9.6589, 80.0226)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'p_mangos_jaffna',
    name: "Mango's Restaurant Jaffna",
    category: 'FOOD',
    tagline: 'The definitive Jaffna crab curry — on the lagoon, exactly as it should be',
    description: 'The most-recommended restaurant in Jaffna. The mud crab arrives from the lagoon each morning. The black curry — ground roasted spices, coconut milk, curry leaves — is the version all other Jaffna crab curries are compared to. The family has been cooking here for thirty years.',
    lat: 9.6589, lng: 80.0226,
    address: 'Lagoon Road, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 21 2 222 871', whatsapp: '+94212222871',
    tier: 'premium',
    photos: [], priceMin: 10, priceMax: 25,
    tags: ['crab-curry', 'lagoon', 'jaffna-cuisine', 'family-run'],
    openingHours: { mon: '11am–10pm', tue: '11am–10pm', wed: '11am–10pm', thu: '11am–10pm', fri: '11am–11pm', sat: '11am–11pm', sun: '11am–9pm' },
    isApproved: true,
  },
  {
    id: 'p_cosy_jaffna',
    name: 'Cosy Restaurant Jaffna',
    category: 'FOOD',
    tagline: 'Market breakfast — idli, vadai, and sambar from the tandoor',
    description: 'The breakfast restaurant for Jaffna market traders. Opens at 5am. The idli is ground overnight and steamed to order. The vadai (savoury donut) is fried in batches every thirty minutes. One of the most authentic Tamil breakfast experiences in Sri Lanka.',
    lat: 9.6615, lng: 80.0088,
    address: 'Kasturiya Road, Jaffna Market, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 77 234 5091', whatsapp: '+94772345091',
    tier: 'partner',
    photos: [], priceMin: 2, priceMax: 6,
    tags: ['breakfast', 'idli', 'vadai', 'market', 'early-opening'],
    openingHours: { mon: '5am–1pm', tue: '5am–1pm', wed: '5am–1pm', thu: '5am–1pm', fri: '5am–1pm', sat: '5am–1pm', sun: '5am–11am' },
    isApproved: true,
  },
  {
    id: 'p_green_hostel_jaffna',
    name: 'The Green Hostel Jaffna',
    category: 'STAY',
    tagline: 'The only proper backpacker hostel in the north — helpful, clean, local knowledge',
    description: 'The go-to for independent travellers in Jaffna. The team knows the region deeply and can advise on Nainativu island ferry, Nagadeepa temple, the Point Pedro lighthouse, and the best places to eat and avoid. Bicycle hire from the hostel.',
    lat: 9.6630, lng: 80.0070,
    address: 'Stanley Road, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 77 765 4321', whatsapp: '+94777654321',
    tier: 'partner',
    photos: [], priceMin: 10, priceMax: 30,
    tags: ['hostel', 'backpacker', 'bicycle-hire', 'local-knowledge'],
    openingHours: { note: 'Open 24 hours. Check-in from 1pm.' },
    isApproved: true,
  },
  {
    id: 'p_jaffna_heritage',
    name: 'Jaffna Heritage Hotel',
    category: 'STAY',
    tagline: 'Colonial mansion converted into the finest hotel in the peninsula',
    description: 'A restored 19th-century mansion in the heart of Jaffna. Twenty-eight rooms, a rooftop pool, and a restaurant serving Jaffna cuisine that the chef learned from three generations of family recipes. The best base for exploring the north.',
    lat: 9.6650, lng: 80.0050,
    address: '99 Kasthuriya Road, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 21 2 228 000', whatsapp: '+94212228000',
    tier: 'premium',
    photos: [], priceMin: 70, priceMax: 160,
    tags: ['colonial', 'rooftop-pool', 'jaffna-cuisine', 'central-location'],
    openingHours: { note: 'Check-in 2pm, check-out 11am.' },
    isApproved: true,
  },
  {
    id: 'p_jaffna_cycling_tour',
    name: 'Jaffna Cycle Stories',
    category: 'EXPERIENCE',
    tagline: 'Half-day bicycle tour of Jaffna peninsula — temples, palmyrah farms, lagoon',
    description: 'The best way to see Jaffna is by bicycle. This four-hour tour covers the Nallur Kovil, the old Dutch fort, the palmyrah toddy tapping villages, and ends at a lagoon-side coconut sambol lunch. Maximum 6 riders.',
    lat: 9.6615, lng: 80.0088,
    address: 'Meets at Jaffna Public Library',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 77 543 2109', whatsapp: '+94775432109',
    tier: 'partner',
    photos: [], priceMin: 18, priceMax: 25,
    tags: ['cycling', 'temple', 'lagoon', 'palmyrah', 'small-group'],
    openingHours: { note: 'Tours at 7am and 3pm. Book 24 hours ahead.' },
    isApproved: true,
  },
  {
    id: 'p_jaffna_market_tour',
    name: 'Vani\'s Market Food Walk',
    category: 'EXPERIENCE',
    tagline: 'Walk the Jaffna market with a local cook — learn what you\'re looking at',
    description: 'Vani has been cooking Jaffna food since she was seven. This two-hour morning walk through the market covers palmyrah products, the fish section, fresh spices, and the dry goods that define northern Sri Lankan cooking. Ends with breakfast at Cosy Restaurant.',
    lat: 9.6615, lng: 80.0088,
    address: 'Jaffna Municipal Market, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 77 654 3201', whatsapp: '+94776543201',
    tier: 'partner',
    photos: [], priceMin: 20, priceMax: 28,
    tags: ['food-walk', 'market', 'local-cook', 'breakfast-included'],
    openingHours: { note: 'Tour at 5:30am only. Ends 7:30am. 5 person max.' },
    isApproved: true,
  },
  {
    id: 'p_jaffna_transport',
    name: 'Jaffna Peninsula Drivers',
    category: 'TRANSPORT',
    tagline: 'Reliable drivers for the Jaffna peninsula — ferries, islands, temples',
    description: 'A network of approved drivers covering Jaffna, Nainativu, Delft Island ferry connections, Nagadeepa, and Kayts. All drivers speak Tamil and English and know the ferry schedules.',
    lat: 9.6620, lng: 80.0060,
    address: 'Jaffna Bus Stand, Jaffna',
    district: 'Jaffna', province: 'NORTHERN',
    phone: '+94 77 444 3322', whatsapp: '+94774443322',
    tier: 'listed',
    photos: [], priceMin: 15, priceMax: 60,
    tags: ['driver', 'island-tours', 'ferry-connection', 'english-speaking'],
    openingHours: { note: 'Available 5am–10pm. WhatsApp to book.' },
    isApproved: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NORTH_CENTRAL PROVINCE — Ancient Kingdom Route
  // Chapters: Anuradhapura (8.3114, 80.4037) | Sigiriya (7.9570, 80.7603)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'p_sanctuary_tissawewa',
    name: 'The Sanctuary at Tissawewa',
    category: 'STAY',
    tagline: 'A colonial rest house inside the Anuradhapura sacred zone — walk to the dagobas',
    description: 'Built by the British in the 1890s as a government rest house. Now a boutique property with twenty-four rooms, tropical gardens, and a pool. The sacred city is a three-minute walk. The dawn cycle to Jetavanaramaya starts from the hotel gate.',
    lat: 8.3114, lng: 80.4037,
    address: 'New Town, Anuradhapura',
    district: 'Anuradhapura', province: 'NORTH_CENTRAL',
    phone: '+94 25 2 222 299', whatsapp: '+94252222299',
    tier: 'premium',
    photos: [], priceMin: 80, priceMax: 180,
    tags: ['colonial', 'sacred-zone', 'cycle-friendly', 'pool'],
    openingHours: { note: 'Check-in 2pm. Bicycle hire available from 5am.' },
    isApproved: true,
  },
  {
    id: 'p_aliya_sigiriya',
    name: 'Aliya Resort & Spa Sigiriya',
    category: 'STAY',
    tagline: 'The resort where the elephants walk through the grounds at dusk',
    description: 'The most dramatic hotel setting in Sri Lanka. The infinity pool faces Sigiriya Rock. At dusk, the resident elephant herd passes through the grounds on their way to the river. The restaurant is one of the best in the Cultural Triangle.',
    lat: 7.9650, lng: 80.7600,
    address: 'Sigiriya Village Road, Sigiriya',
    district: 'Matale', province: 'NORTH_CENTRAL',
    phone: '+94 66 2 280 280', whatsapp: null,
    website: 'https://aliyaresort.com',
    tier: 'premium',
    photos: [], priceMin: 200, priceMax: 450,
    tags: ['luxury', 'infinity-pool', 'sigiriya-views', 'elephants-in-grounds'],
    openingHours: { note: 'Check-in 2pm. Book minimum 2 nights.' },
    isApproved: true,
  },
  {
    id: 'p_jetwing_vil_uyana',
    name: 'Jetwing Vil Uyana',
    category: 'STAY',
    tagline: 'Eco-villas on a reclaimed rice paddy — nature reserve, no TV, no noise',
    description: 'Twenty-five villas on stilts in a restored wetland that now teems with birds, buffaloes, and river otters. No pool, no gym, no organised entertainment — just the paddy fields and the sound of kingfishers. The silence is the attraction.',
    lat: 7.9570, lng: 80.7500,
    address: 'Sigiriya, Dambulla',
    district: 'Matale', province: 'NORTH_CENTRAL',
    phone: '+94 66 2 279 879', whatsapp: null,
    website: 'https://jetwinghotels.com',
    tier: 'premium',
    photos: [], priceMin: 250, priceMax: 500,
    tags: ['eco', 'wetland', 'birdwatching', 'silence', 'no-tv'],
    openingHours: { note: 'Check-in 2pm. Min 2 nights recommended.' },
    isApproved: true,
  },
  {
    id: 'p_sigiriya_guide',
    name: 'Cultural Triangle Guides',
    category: 'EXPERIENCE',
    tagline: 'Licensed government guides for Sigiriya and Anuradhapura',
    description: 'A co-operative of fifteen government-licensed guides covering Sigiriya, Anuradhapura, Polonnaruwa, and Dambulla. They interpret the frescoes, explain the hydraulic system, and know which areas have the fewest crowds at which times.',
    lat: 7.9570, lng: 80.7603,
    address: 'Sigiriya Main Gate, Sigiriya',
    district: 'Matale', province: 'NORTH_CENTRAL',
    phone: '+94 77 654 3212', whatsapp: '+94776543212',
    tier: 'partner',
    photos: [], priceMin: 12, priceMax: 20,
    tags: ['licensed-guide', 'sigiriya', 'anuradhapura', 'small-group'],
    openingHours: { note: 'Available from 6:30am at the main gates. Book by WhatsApp.' },
    isApproved: true,
  },
  {
    id: 'p_milano_anuradhapura',
    name: 'Milano Restaurant Anuradhapura',
    category: 'FOOD',
    tagline: 'The best rice and curry in Anuradhapura — forty years of consistent cooking',
    description: 'Do not be misled by the Italian name. Milano has been serving Sri Lankan food since 1981 and the quality has not varied in forty years. The dhal curry, the jackfruit curry, and the pol sambol are the order. Cash only.',
    lat: 8.3150, lng: 80.4020,
    address: 'Main Street, Anuradhapura New Town',
    district: 'Anuradhapura', province: 'NORTH_CENTRAL',
    phone: '+94 25 2 222 543', whatsapp: null,
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 8,
    tags: ['rice-and-curry', 'institution', 'cash-only', 'vegetarian-friendly'],
    openingHours: { mon: '6am–9pm', tue: '6am–9pm', wed: '6am–9pm', thu: '6am–9pm', fri: '6am–9pm', sat: '6am–9pm', sun: '7am–8pm' },
    isApproved: true,
  },
  {
    id: 'p_sigiriya_restaurant',
    name: 'Sigiriya Rock Cafe',
    category: 'FOOD',
    tagline: 'Cold drinks, fried rice, and Sigiriya views from a shaded garden',
    description: 'The best-located cafe near the Sigiriya entrance. Not a destination restaurant — this is for cold coconuts after the climb, a plate of fried rice and devilled chicken while waiting for the afternoon light. The garden is shaded. The view is Sigiriya Rock.',
    lat: 7.9600, lng: 80.7580,
    address: 'Sigiriya Village, Sigiriya',
    district: 'Matale', province: 'NORTH_CENTRAL',
    phone: '+94 66 2 280 119', whatsapp: '+94662280119',
    tier: 'partner',
    photos: [], priceMin: 4, priceMax: 12,
    tags: ['post-climb', 'cold-drinks', 'garden', 'sigiriya-views'],
    openingHours: { mon: '7am–8pm', tue: '7am–8pm', wed: '7am–8pm', thu: '7am–8pm', fri: '7am–8pm', sat: '7am–8pm', sun: '7am–8pm' },
    isApproved: true,
  },
  {
    id: 'p_anuradhapura_cycle',
    name: 'Anuradhapura Bicycle Hire',
    category: 'TRANSPORT',
    tagline: 'Rent a bicycle at the sacred city gate — the only way to see the scale of it',
    description: 'Twenty bicycles available for hire at the northern gate of the sacred city. The site is 40km² — a bicycle is not optional. Helmets and locks included. Route maps showing the main monuments in order are printed and laminated for each hire.',
    lat: 8.3114, lng: 80.4037,
    address: 'Northern Gate, Sacred City, Anuradhapura',
    district: 'Anuradhapura', province: 'NORTH_CENTRAL',
    phone: '+94 77 234 5692', whatsapp: '+94772345692',
    tier: 'listed',
    photos: [], priceMin: 3, priceMax: 5,
    tags: ['bicycle-hire', 'route-map', 'half-day', 'full-day'],
    openingHours: { note: 'Open 6am–5pm daily. Return before 5:30pm.' },
    isApproved: true,
  },
  {
    id: 'p_cultural_transport',
    name: 'Cultural Triangle Car Service',
    category: 'TRANSPORT',
    tagline: 'Driver-guides covering Sigiriya, Anuradhapura, Polonnaruwa and Dambulla',
    description: 'The Cultural Triangle covers four UNESCO sites spread across 150km. This service provides A/C vehicles with drivers who know all four sites and can plan the most efficient route. Full-day and multi-day tours available from Colombo or Kandy.',
    lat: 7.9570, lng: 80.7603,
    address: 'Inamaluwa Junction, Sigiriya',
    district: 'Matale', province: 'NORTH_CENTRAL',
    phone: '+94 77 888 7766', whatsapp: '+94778887766',
    tier: 'partner',
    photos: [], priceMin: 60, priceMax: 150,
    tags: ['cultural-triangle', 'a/c', 'driver-guide', 'multi-site'],
    openingHours: { note: 'Available 5am–9pm. Book 24h ahead for early departures.' },
    isApproved: true,
  },
]

// ─── Featured partner assignments ────────────────────────────────────────────
// These are editorial picks — shown first, above proximity results.
// Format: { chapterId, partnerId, displayOrder }

const FEATURED: { chapterId: string; partnerId: string; displayOrder: number }[] = [
  // Colombo chapters
  { chapterId: 'arc_colombo_street_food_ch1', partnerId: 'p_colombo_food_tour', displayOrder: 0 },
  { chapterId: 'arc_colombo_street_food_ch1', partnerId: 'p_upalis', displayOrder: 1 },
  { chapterId: 'arc_colombo_street_food_ch1', partnerId: 'p_nomads_colombo', displayOrder: 2 },
  { chapterId: 'arc_colombo_street_food_ch2', partnerId: 'p_dinemore', displayOrder: 0 },
  { chapterId: 'arc_colombo_street_food_ch2', partnerId: 'p_fort_tuktuk', displayOrder: 1 },
  { chapterId: 'arc_colombo_street_food_ch3', partnerId: 'p_pagoda_tea', displayOrder: 0 },
  { chapterId: 'arc_colombo_street_food_ch3', partnerId: 'p_colombo_cycling', displayOrder: 1 },
  { chapterId: 'arc_colombo_street_food_ch3', partnerId: 'p_cinnamon_grand', displayOrder: 2 },

  // Yala chapters
  { chapterId: 'arc_yala_leopard_ch1', partnerId: 'p_yala_jeep_safari', displayOrder: 0 },
  { chapterId: 'arc_yala_leopard_ch1', partnerId: 'p_yala_wild_camp', displayOrder: 1 },
  { chapterId: 'arc_yala_leopard_ch1', partnerId: 'p_chena_huts', displayOrder: 2 },
  { chapterId: 'arc_yala_leopard_ch2', partnerId: 'p_yala_jeep_safari', displayOrder: 0 },
  { chapterId: 'arc_yala_leopard_ch2', partnerId: 'p_yala_camp_kitchen', displayOrder: 1 },
  { chapterId: 'arc_yala_leopard_ch3', partnerId: 'p_chena_huts', displayOrder: 0 },
  { chapterId: 'arc_yala_leopard_ch3', partnerId: 'p_yala_jeep_safari', displayOrder: 1 },

  // Udawalawe chapters
  { chapterId: 'arc_udawalawe_elephants_ch1', partnerId: 'p_udawalawe_safari', displayOrder: 0 },
  { chapterId: 'arc_udawalawe_elephants_ch1', partnerId: 'p_centauria_wild', displayOrder: 1 },
  { chapterId: 'arc_udawalawe_elephants_ch1', partnerId: 'p_udawalawe_food', displayOrder: 2 },
  { chapterId: 'arc_udawalawe_elephants_ch2', partnerId: 'p_elephant_watch', displayOrder: 0 },
  { chapterId: 'arc_udawalawe_elephants_ch2', partnerId: 'p_kalus_hideaway', displayOrder: 1 },
  { chapterId: 'arc_udawalawe_elephants_ch2', partnerId: 'p_udawalawe_food', displayOrder: 2 },

  // Surf chapters
  { chapterId: 'arc_surf_south_coast_ch1', partnerId: 'p_weligama_surf_school', displayOrder: 0 },
  { chapterId: 'arc_surf_south_coast_ch1', partnerId: 'p_wijaya_kitchen', displayOrder: 1 },
  { chapterId: 'arc_surf_south_coast_ch1', partnerId: 'p_dream_surf_hostel', displayOrder: 2 },
  { chapterId: 'arc_surf_south_coast_ch1', partnerId: 'p_taprobana', displayOrder: 3 },
  { chapterId: 'arc_surf_south_coast_ch2', partnerId: 'p_madiha_surf', displayOrder: 0 },
  { chapterId: 'arc_surf_south_coast_ch2', partnerId: 'p_mango_cafe', displayOrder: 1 },
  { chapterId: 'arc_surf_south_coast_ch2', partnerId: 'p_south_transport', displayOrder: 2 },
  { chapterId: 'arc_surf_south_coast_ch3', partnerId: 'p_hiriketiya_bowls', displayOrder: 0 },
  { chapterId: 'arc_surf_south_coast_ch3', partnerId: 'p_anantara_hiriketiya', displayOrder: 1 },

  // Ella chapters
  { chapterId: 'arc_ella_trails_ch1', partnerId: 'p_cafe_chill_ella', displayOrder: 0 },
  { chapterId: 'arc_ella_trails_ch1', partnerId: 'p_ella_train_booking', displayOrder: 1 },
  { chapterId: 'arc_ella_trails_ch1', partnerId: 'p_98_acres', displayOrder: 2 },
  { chapterId: 'arc_ella_trails_ch1', partnerId: 'p_ella_adventure', displayOrder: 3 },
  { chapterId: 'arc_ella_trails_ch2', partnerId: 'p_ella_adventure', displayOrder: 0 },
  { chapterId: 'arc_ella_trails_ch2', partnerId: 'p_ella_flower_garden', displayOrder: 1 },
  { chapterId: 'arc_ella_trails_ch2', partnerId: 'p_ella_gap_restaurant', displayOrder: 2 },

  // Tea country chapters
  { chapterId: 'arc_tea_country_reset_ch1', partnerId: 'p_pedro_tours', displayOrder: 0 },
  { chapterId: 'arc_tea_country_reset_ch1', partnerId: 'p_heritance_tea', displayOrder: 1 },
  { chapterId: 'arc_tea_country_reset_ch1', partnerId: 'p_nuwara_eliya_cycling', displayOrder: 2 },
  { chapterId: 'arc_tea_country_reset_ch2', partnerId: 'p_lakeside_ne', displayOrder: 0 },
  { chapterId: 'arc_tea_country_reset_ch2', partnerId: 'p_grand_hotel_ne', displayOrder: 1 },
  { chapterId: 'arc_tea_country_reset_ch2', partnerId: 'p_ne_transport', displayOrder: 2 },
  { chapterId: 'arc_tea_country_reset_ch3', partnerId: 'p_ne_transport', displayOrder: 0 },
  { chapterId: 'arc_tea_country_reset_ch3', partnerId: 'p_heritance_tea', displayOrder: 1 },
  { chapterId: 'arc_tea_country_reset_ch3', partnerId: 'p_hill_club', displayOrder: 2 },

  // Galle Fort chapters
  { chapterId: 'arc_galle_fort_ch1', partnerId: 'p_fort_walking_tour', displayOrder: 0 },
  { chapterId: 'arc_galle_fort_ch1', partnerId: 'p_amangalla', displayOrder: 1 },
  { chapterId: 'arc_galle_fort_ch1', partnerId: 'p_dutch_market_cafe', displayOrder: 2 },
  { chapterId: 'arc_galle_fort_ch2', partnerId: 'p_fort_walking_tour', displayOrder: 0 },
  { chapterId: 'arc_galle_fort_ch2', partnerId: 'p_galle_fort_hotel', displayOrder: 1 },
  { chapterId: 'arc_galle_fort_ch2', partnerId: 'p_barefoot_galle', displayOrder: 2 },
  { chapterId: 'arc_galle_fort_ch3', partnerId: 'p_fortaleza', displayOrder: 0 },
  { chapterId: 'arc_galle_fort_ch3', partnerId: 'p_galle_cycling', displayOrder: 1 },
  { chapterId: 'arc_galle_fort_ch3', partnerId: 'p_fort_printers', displayOrder: 2 },
  { chapterId: 'arc_galle_fort_ch3', partnerId: 'p_amangalla', displayOrder: 3 },

  // Jaffna chapters
  { chapterId: 'arc_jaffna_table_ch1', partnerId: 'p_cosy_jaffna', displayOrder: 0 },
  { chapterId: 'arc_jaffna_table_ch1', partnerId: 'p_jaffna_market_tour', displayOrder: 1 },
  { chapterId: 'arc_jaffna_table_ch1', partnerId: 'p_green_hostel_jaffna', displayOrder: 2 },
  { chapterId: 'arc_jaffna_table_ch1', partnerId: 'p_jaffna_cycling_tour', displayOrder: 3 },
  { chapterId: 'arc_jaffna_table_ch2', partnerId: 'p_mangos_jaffna', displayOrder: 0 },
  { chapterId: 'arc_jaffna_table_ch2', partnerId: 'p_jaffna_heritage', displayOrder: 1 },
  { chapterId: 'arc_jaffna_table_ch2', partnerId: 'p_jaffna_transport', displayOrder: 2 },

  // Ancient Kingdom chapters
  { chapterId: 'arc_ancient_kingdoms_ch1', partnerId: 'p_anuradhapura_cycle', displayOrder: 0 },
  { chapterId: 'arc_ancient_kingdoms_ch1', partnerId: 'p_sanctuary_tissawewa', displayOrder: 1 },
  { chapterId: 'arc_ancient_kingdoms_ch1', partnerId: 'p_milano_anuradhapura', displayOrder: 2 },
  { chapterId: 'arc_ancient_kingdoms_ch1', partnerId: 'p_sigiriya_guide', displayOrder: 3 },
  { chapterId: 'arc_ancient_kingdoms_ch2', partnerId: 'p_sigiriya_guide', displayOrder: 0 },
  { chapterId: 'arc_ancient_kingdoms_ch2', partnerId: 'p_aliya_sigiriya', displayOrder: 1 },
  { chapterId: 'arc_ancient_kingdoms_ch2', partnerId: 'p_sigiriya_restaurant', displayOrder: 2 },
  { chapterId: 'arc_ancient_kingdoms_ch2', partnerId: 'p_jetwing_vil_uyana', displayOrder: 3 },
]

// ─── Seed runner ──────────────────────────────────────────────────────────────

async function seedPartners() {
  console.log('Seeding partners...')

  let created = 0
  let skipped = 0

  for (const p of PARTNERS) {
    await db
      .insert(partners)
      .values({
        ...p,
        openingHours: p.openingHours ?? null,
      })
      .onConflictDoUpdate({
        target: partners.id,
        set: {
          name: p.name,
          tagline: p.tagline,
          description: p.description,
          tier: p.tier,
          isApproved: p.isApproved,
        },
      })
    console.log(`  ✓ ${p.name} (${p.category} · ${p.province} · ${p.tier})`)
    created++
  }

  console.log(`\nSeeding ${FEATURED.length} featured chapter assignments...`)

  for (const f of FEATURED) {
    await db
      .insert(chapterFeaturedPartners)
      .values(f)
      .onConflictDoNothing()
  }

  console.log(`\n✅ ${created} partners seeded, ${FEATURED.length} chapter assignments created.`)
  process.exit(0)
}

seedPartners().catch((err) => {
  console.error('Partner seed failed:', err)
  process.exit(1)
})
